### ISSUE TITLE
BUG: Newest Version of Infernal Robotics not appearing in the GUI

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/CKAN-GUI#108]
On CKAN GUI Client v1.6.13-0-g0000000 (beta) for KSP 1.0.2, I am not seeing the newest version of Infernal Robotics for download, which is only v0.21

When checking https://github.com/KSP-CKAN/CKAN-meta/tree/master/InfernalRobotics I see that there is version 0.21.2 available for download.

Expected:
CKAN's GUI should list the 0.21.2 for download

Actual:
CKAN is not showing a version newer than v0.21 as available for download.

Impact:
This is causing UI bugs, specifically one related to the Infernal Robotics UI button replicating in the toolbar, because CKAN is forcing an outdated version of Infernal Robotics on the player, despite meta data existing for the newer version of the mod.

**Comment by Almagnus1** [comment]
Potential Fix: https://github.com/KSP-CKAN/CKAN-core/pull/109

**Comment by sergioberg** [comment]
https://github.com/KSP-CKAN/CKAN-support/issues/133

**Comment by Dazpoet** [comment]
This has been resolved, closing.
