### ISSUE TITLE
New binary is not executable after update (Linux)

### ISSUE THREAD

**Issue by vtdmhd** [KSP-CKAN/CKAN-GUI#117]
I place the CKAN binry in ~/bin/ckan, after every update I have to manually chmod it back.
Perhaps saving the rights and restoring them back during the update will solve the problem.

**Comment by mgsdk** [comment]
We've had this issue before, but I though we had gotten around to fixing it. Just to make sure, can you post the following?

1. CKAN version.
2. Mono version (mono -V)
3. Linux distribution and version

**Comment by vtdmhd** [comment]
1) CKAN v1.6.16-0-g0000000 (beta)
2) Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)  
3) Debian Stretch, Linux  3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3 (2015-04-23) x86_64 GNU/Linux

**Comment by mgsdk** [comment]
@vtdmhd Sorry it took so long. From now on, you should no longer need to +x your updated ckan.exe files. This will only take effect on the update after the next release though.
