### ISSUE TITLE
Suggestion: import/export of installed mod list

### ISSUE THREAD

**Issue by cwc** [KSP-CKAN/CKAN-GUI#121]
I think this would be a pretty convenient feature. A couple of use cases off the top of my head:

* Admin of modded multiplayer servers can distribute a list of mods. Players could then install all required mods quickly and easily by importing the list in the CKAN client.

* Players can maintain separate lists of mods for solo and multiplayer play, without having to keep multiple KSP installations. Playing a modded career, but want to jump on a vanilla server? Export the mod list, deactivate the mods, and go play. Import and reinstall from the list when done.

* Streamers and "Let's Play"ers can publish their mod list for use by viewers.

**Comment by cwc** [comment]
I'm willing to implement this, but I wanted to seek feedback on the idea first. Especially if there are any 'gotchas' I'd be unaware of, as I'm unfamiliar with the app's codebase.

**Comment by RichardLake** [comment]
The main gotcha would be the GUI codebase is ... messy. Other than that it should be fairly easy to implement and is a requested feature. One thing to keep in mind is the %game_dir%/CKAN/installed-default.ckan file - it contains a metapackage of the currently installed mods. As such a export could just be a copy/rename of this file and a import via install from ckan menu option.

**Comment by Dazpoet** [comment]
import of installed mod list already exists since you can easily File -> Install from .ckan -> choose a metapackage.

The missing part would be a gui way to save a copy of installed-default.ckan and we should be good to go?

**Comment by cwc** [comment]
Nice, glad I asked first! Didn't realize that metapackage was already generated. It looks like the core currently will always name it 'installed-default.ckan', so I'll enable saving a copy of that.
