### ISSUE TITLE
GUI lists as available mods that have unsatisfied indirect dependencies

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-GUI#2]
_From @Dazpoet on December 21, 2014 17:59_

The Changeset tab does not appear and therefor installation is impossible.

_Copied from original issue: KSP-CKAN/CKAN#665_

**Comment by Dazpoet** [comment]
From what I gather this was resolved through https://github.com/KSP-CKAN/CKAN-GUI/pull/28 and seeing as I'm the initial issuecreator and cannot seem to reproduce this even though I tried making some nasty metapackages to do so I'll close it :)
