### ISSUE TITLE
Show why a mod is automatically installed

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-GUI#4]
_From @xZise on December 15, 2014 14:55_

When installing a mod, it might select other mods to be installed alongside and it would be helpful to know if a mod which was automatically installed because it was required, recommended or suggested (if those were enabled).

_Copied from original issue: KSP-CKAN/CKAN#589_

**Comment by pjf** [comment]
Re-opening original issue. :)
