### ISSUE TITLE
Dependencies not installed

### ISSUE THREAD

**Issue by Goz3rr** [KSP-CKAN/CKAN-GUI#47]
I wanted to change my regular B9 install to a CKAN install, removed all folder from my GameData, but forgot the stock ships which resulted in CKAN giving out an error saying it wouldn't install and reverted my GameData folder. I removed these files and installed again (saw some messages about it installing from cache) but then I got these errors:

    The following inconsistecies were found:
    B9 requires CrossFeedEnabler but nothing provides it
     * B9 requires KineTechAnimation but nothing provides it
     * B9 requires ResGen but nothing provides it

Uninstalling B9 through CKAN and then reinstalling it fixed this problem, so I suspect it's an issue with CKAN not getting these dependencies when installing from cache?

The version from the about menu says v1.5.6-0-g0000000 (beta)

**Comment by mgsdk** [comment]
The installing from cache message should only be relevant for the download of the files, the consistency check should already have been performed prior to this. Could you upload a copy of your registry.json and installed-default.ckan in KSP-Directory/CKAN/?

**Comment by Goz3rr** [comment]
Alright here you go:

http://goz3rr.me/share/registry.json
http://goz3rr.me/share/installed-default.ckan

I'm not sure if they're of any help though because by now i've already installed B9
