### ISSUE TITLE
GUI colors under Linux

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN-GUI#5]
_From @AlexanderDzhoganov on November 20, 2014 11:44_

There seems to be something funky going on with control backgrounds on Linux i.e. the colors don't match everywhere.
Here is a screenshot to show the problem - http://i.imgur.com/CV0eEoj.png

_Copied from original issue: KSP-CKAN/CKAN#422_

**Comment by toadicus** [comment]
I can confirm as well.

https://imgrush.com/E9u9sSPSzoDw

vs 

https://imgrush.com/DCiqQqiYs6b4

**Comment by mgsdk** [comment]
At last the KDE part may be related to https://bugzilla.novell.com/show_bug.cgi?id=670698, which seem to never have been fixed.
