### ISSUE TITLE
"Installed" filter shows empty list

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN-GUI#67]
Issue noted since ckan v1.6.3; confirmed with ckan v1.6.5.

Selecting the "installed" filter shows no mods, despite the drop-down showing the correct number of mods which are installed.

Using the command line "list" function does show all the installed mods.

Debian GNU/Linux 8 "jessie"; x64

**Comment by AlexanderDzhoganov** [comment]
Can't reproduce here, maybe somebody else can?

**Comment by mwerle** [comment]
Sorry, I forgot to update; this happens with one of my KSP installs, another one is fine. But it does so consistently for the one with this issue.  I'll try to isolate the cause and add additional info and/or workaround/fix.

**Comment by Dazpoet** [comment]
Unable to reproduce on any of my installs, I managed to force an empty list by adding some spaces to the searchbar but it did not persist through a restart of the gui.

**Comment by mwerle** [comment]
Sorry; I got busy with Real Life and it slipped off my radar since then.
I cannot currently repro with v1.6.6.0 of the CKAN client with the install which had the issue, so closing this.  If it happens again I'll raise a new issue.
Thanks for investigating.
