### ISSUE TITLE
Suggestion: add button to clear filter textbox

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN-GUI#70]
Add a button to clear the filter textbox next to it.  Further; button should be disabled if filter textbox is empty.

**Comment by vtdmhd** [comment]
Ctrl+A, Del

**Comment by mwerle** [comment]
Yes, I know about keyboard shortcuts. I can also use the command-line interface and grep.
But it's a GUI, it should (IMHO) have GUI elements for its functions.

It was just a suggestion in either case; feel free to mark it "won't fix".

**Comment by vtdmhd** [comment]
I agree completely, but there must be a limit somewhere. Otherwise, we'll end up with an on-screen keyboard near every textbox

**Comment by mwerle** [comment]
Sure; there is definitely a requirement for balance.  My suggestion was based on 2 points:

1) Having a clear/reset button is quite a common GUI element for certain types of text input fields, in my experience filters is one of them.
2) Having the button disable when the input field is empty provides visual feedback if there is some leftover whitespace in the field (which, for some reason, I've had often enough that I now check for it as a matter of course - maybe that's just an oddity of how I interact with programs)

Alternatively for (2) leading/trailing whitespace could be simply trimmed from the search filters, which is fairly common practice as well.

**Comment by mgsdk** [comment]
I have some code for this in the works with a few issues:
1. The text goes under the button.
2. No graphic for the button, open for suggestions.
