### ISSUE TITLE
CKAN client Custom filter

### ISSUE THREAD

**Issue by sshadowwraith** [KSP-CKAN/CKAN-GUI#79]
I have noticed that in the Filter dropdown, the "Custom" option doesn't do anything and cannot be selected. I am not certain that this is actually an issue, but the fact that it is there, but seems to have no purpose kinda tweaks my curiosity. Is it a feature that is supposed to be upcoming?

**Comment by RichardLake** [comment]
I'm not sure if there are plans for it. However as it doesn't currently do anything there is no need to display it to the user.

**Comment by Dazpoet** [comment]
Seems this wasn't autoclosed by #83 so I'll close it now.
