### ISSUE TITLE
Inability to uninstall outdated mods

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/CKAN-GUI#86]
One of the things I do not like about CKAN is when you install a mod, then the game updates, and then you lose the ability to uninstall mods that are not compatible with the current game, yet are installed.

What I would like to see is the entry for an outdated mod change to red.  If this is possible, have the far left check box turn into an X, which will remove the mod should I want to.

Either way, CKAN shouldn't forget what's installed, especially if I used CKAN to install a mod, and then the game updates.

It's forcing me to wipe the game directory and reinstall via Steam so I can purge whatever mods may have been installed - not a fun process.

**Comment by Dazpoet** [comment]
You can easily solve this through commandline by doing `ckan list` where you see which mods are incompatible and then you `ckan remove <mod>` to remove if from CKAN. Unfortunatly this is not yet available through the GUI client.

**Comment by Almagnus1** [comment]
That's not helpful to the average user, as they are going to have no clue how to use command line syntax, much less how to alter a shortcut to work that change in.

This is something that must be made easily accessible in the GUI, like a setting option that's turned on by default.

**Comment by Dazpoet** [comment]
I'm sorry for providing a solution to your problem.

I'm marking this as an enhancement request.

**Comment by Almagnus1** [comment]
It's not a solution, it's a workaround for the issue - there's a difference.  It's also the second of two workarounds in this issue, the first being a wipe and reinstall of KSP (using Steam to do the reinstall), then adding in the mods via CKAN.

The problem is that the UI will not report all mods that are installed, which should be default behavior because that is the expectation of players when they are using CKAN.

Because the UI is not acting in a manner that makes sense - that is, CKAN GUI is not correctly tracking what it has, and hasn't, installed, it's going to cause install folder bloat, as there will be mods that some users completely forget about, or hit other frustrating issues where things don't work and they do not know why, as they see everything in CKAN being up to date.

This behavior is undesired, and it is a bug.
