### ISSUE TITLE
Setting to refresh on CKAN client launch

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/CKAN-GUI#87]
I would like a config option to have CKAN automatically sync with the server once the client loads, so I can see if there's any mods that need updating, or if there's anything new to add before launching the game itself.

**Comment by Andy81le** [comment]
I would also like to see this.

**Comment by politas** [comment]
+1. I can see little reason not to refresh automatically at startup. I'm willing to believe there are users who wouldn't wish this behaviour, but I suspect many to most would appreciate it, at least as an option.

**Comment by dss539** [comment]
I second this request. As a new user of this tool, I failed to refresh the repository which left me in a confused state until Daz was able to clear it up for me.
