### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Andy81le** [KSP-CKAN/CKAN-GUI#93]
It would be practical to have categories in order to be able to choose mods and plugins more easily. A good starting point for categories would be that of the 'Community Mods and Plugins Library' (http://forum.kerbalspaceprogram.com/threads/55401-Community-Mods-and-Plugins-Library). This would also give the modding community a bit more consistency.

**Comment by politas** [comment]
This would be good.

**Comment by Shaggygoblin** [comment]
+1, similar to how parts are 'catagorized' in KSP, a 'tag(s)' can be utilized to denote parts only, visual/audio, modules (adds/changes functionality).  RemoteTech would be a Part and Module, RasterPropMonitorCore would be a Module only, KW Rocketry would be Parts only.  If a Parts Only pack had a dependency which contained a Module tag, then possibly append the Module tag to the parent, thus B9 would inherit it's Module tag from it's dependent, FirespitterCore.
Just thinking out loud, sorry.
But still +1 on the Categories/Tabs in CKAN.

**Comment by dewiniaid** [comment]
+1 for tags/categories, but please allow metadata to support multiple categories -- and have a built in "uncategorized" category for mods lacking categories.

It'd also be neat if the tags included what -kinds- of parts are involved, e.g. things like "ISRU", "Unmanned", "Manned", "Station", "Science", etc -- in addition to generic things like "Tech Tree", 'Career", "Physics"

**Comment by damerell** [comment]
An obvious characterisation would be "library" mods which are only installed as dependencies - which add nothing to the game in and of themselves.

**Comment by Dazpoet** [comment]
How would people feel about a "hidden" category filled with mods like the "library" mods mentioned above that was hidden from the user from the start? There has been some discussion like that over in https://github.com/KSP-CKAN/CKAN/issues/803 and now that https://github.com/KSP-CKAN/CKAN-GUI/pull/137 is in the works it might be more feasible than before to consider such a thing.

I will assume that a great part of this request is based on the aspect of wanting to shop for mods more easily, but also to some degree to resolve some of the clutter that is the CKAN modlist? I think a hidden category (which could easily be shown if a user wanted it) could be a good solution to the latter and it would perhaps also make shopping for mods easier?

As for the implementation I would assume this would require us to update a *lot* of metadata making https://github.com/KSP-CKAN/CKAN/issues/947 extremely relevant.

**Comment by plague006** [comment]
Would hiding library mods cause an issue where users uninstall the mod relying on the library but can't find the actual library to uninstall it?

**Comment by politas** [comment]
If the "Hidden" category was implemented with a change to the default filter, that could work. Perhaps then there could be an "Unused Libraries" filter that lists all such "hidden" mods that nothing currently depends on, to cover @plague006's case.

**Comment by Dazpoet** [comment]
We solve it with https://github.com/KSP-CKAN/CKAN/issues/978 :)

**Comment by dewiniaid** [comment]
I think that categories/tags should be descriptive, rather than being used
directly to trigger any sort of behavior.  "Hidden" tells me as a user
nothing about a particular mod.  So, from a metadata/spec perspective, it
seems wrong.

Now, if a compatible client (e.g. this one) wants to attach a default
behavior to -- say -- hide uninstalled mods that ONLY have the "library"
tag, that seems more appropriate.  Of course, if we have an
aptitude/synaptic-like tree view of mods by category, this is a non-issue
because all the libraries will be segregated into their own category
anyways.

**Comment by pjf** [comment]
Merged over into KSP-CKAN/CKAN!
